---
- name: Playbook to configure nginx-ldap-auth
  hosts: all
  become: true
  tasks:
    - include_tasks: ansible/tasks/main.yml
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted